### ISSUE TITLE
datasource elasticsearch

### ISSUE THREAD

**Issue by cosmos1978** [marcusolsson/grafana-gantt-panel#68]
I always get this error when enabling the gantt plugin.

An unexpected error happened
DetailsTypeError: Cannot read properties of undefined (reading 'enabled')

    at zn (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:275:590)
    at div
    at div
    at tr (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:393:501)
    at div
    at t (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:426:3233)
    at div
    at t (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:426:5184)
    at _r (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:426:10798)
    at div
    at div
    at ia (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:486:6049)
    at v (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:971570)
    at div
    at Mi (http://grafana.elkprod.idtv.bc:3000/public/build/DashboardPage.6839ffb2aed352838f3a.js:574:3581)
    at DashboardPage
    at v (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:971570)
    at n (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:942012)
    at zi (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:6393:193)
    at t (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:989568)
    at t (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:991589)
    at main
    at t (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:986186)
    at div
    at Ws (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:2156:1022)
    at d (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:4480:26210)
    at Sl (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:2868:458)
    at Tl (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:2868:1006)
    at l (http://grafana.elkprod.idtv.bc:3000/public/build/633.6839ffb2aed352838f3a.js:2:969088)
    at Oo (http://grafana.elkprod.idtv.bc:3000/public/build/7095.6839ffb2aed352838f3a.js:6473:384)

**Comment by marcusolsson** [comment]
Thank you for reporting! I'm unable to reproduce this on the latest version of the plugin, running Grafana 8.4.2. What plugin version and Grafana version are you running this on?
